- id: arxiv:2608.16669
  description: We introduce an interpretable framework that links molecular states to tissue morphology, turning gene expression prediction from H&E into a tool for discovering the morphological concepts underlying tumour biology.
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
# date: 2020-12-4
# buttons:
#   - type: manubot
#     link: https://greenelab.github.io/meta-review/
#   - type: source
#     text: Manuscript Source
#     link: https://github.com/greenelab/meta-review
#   - type: website
#     link: http://manubot.org/
# repo: greenelab/meta-review

# Recent work / preprints

- id: doi:10.1158/2159-8290.CD-24-1738

- id: doi:10.1101/2022.09.23.509133
  description: We integrate spatial transcriptomics and tissue morphology to show how transcriptionally defined tumour cell states correspond to distinct patterns of spatial organisation and tissue architecture.
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  

# Published papers

- id: doi:10.1186/s13046-022-02519-7

- id: doi:10.1038/s41467-021-26059-4

- id: doi:10.3390/cancers13051097

- id: doi:10.1093/neuonc/noaa091

- id: doi:10.1242/jcs.245043

- id: doi:10.1073/pnas.1908762116

- id: doi:10.1038/s41598-019-48771-4

- id: doi:10.1073/pnas.1715911114

- id: doi:10.1242/dev.101063

- id: doi:10.1016/j.cell.2014.10.027
